# Generated by Django 6.0.1 on 2026-01-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='swiggyDB',
            fields=[
                ('oderID', models.IntegerField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=10)),
                ('foodamount', models.FloatField()),
                ('Email', models.EmailField(max_length=254)),
                ('orderdate', models.DateField()),
                ('Mobile_no', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('deliveryamount', models.FloatField()),
            ],
        ),
    ]
